
namespace POD_Chat.Base.Enum
{
    public enum ChatMessageType
    {
        CREATE_THREAD = 1,
        MESSAGE = 2,
        SENT = 3,
        DELIVERY = 4,
        SEEN = 5,
        PING = 6,
        BLOCK = 7,
        UNBLOCK = 8,
        LEAVE_THREAD = 9,
        RENAME = 10,
        ADD_PARTICIPANT = 11,
        GET_STATUS = 12,
        GET_CONTACTS = 13,
        GET_THREADS = 14,
        GET_HISTORY = 15,
        CHANGE_TYPE = 16,
        REMOVED_FROM_THREAD = 17,
        REMOVE_PARTICIPANT = 18,
        MUTE_THREAD = 19,
        UN_MUTE_THREAD = 20,
        UPDATE_THREAD_INFO = 21,
        FORWARD_MESSAGE = 22,
        USER_INFO = 23,
        USER_STATUS = 24,
        GET_BLOCKED = 25,
        RELATION_INFO = 26,
        THREAD_PARTICIPANTS = 27,
        EDIT_MESSAGE = 28,
        DELETE_MESSAGE = 29,
        THREAD_INFO_UPDATED = 30,
        LAST_SEEN_UPDATED = 31,
        SEEN_MESSAGE_LIST = 32,
        IS_NAME_AVAILABLE = 34,
        DELIVERED_MESSAGE_LIST = 33,
        JOIN_THREAD = 39,
        INTERACT_MESSAGE = 40,
        SPAM_PV_THREAD = 41,
        SET_ROLE_TO_USER = 42,
        REMOVE_ROLE_FROM_USER = 43,
        CLEAR_HISTORY = 44,
        SIGNAL_MESSAGE = 45,
        PIN_THREAD = 48,
        UNPIN_THREAD = 49,
        PIN_MESSAGE = 50,
        UNPIN_MESSAGE = 51,
        UPDATE_PROFILE = 52,
        USER_ROLES = 54,
        ALL_UNREAD_MESSAGE_COUNT = 61,
        CREATE_BOT = 62,
        DEFINE_BOT_COMMAND = 63,
        START_BOT = 64,
        STOP_BOT = 65,
        ERROR = 999,

        CALL_REQUEST = 70,
        //Type 71 never fire from server to client only client send 71 to server
        ACCEPT_CALL = 71,
        REJECT_CALL = 72,
        DELIVERED_CALL_REQUEST = 73,
        START_CALL = 74,
        END_CALL_REQUEST = 75,
        END_CALL = 76,
        GET_CALLS = 77,
        GROUP_CALL_REQUEST = 91,
        LEAVE_CALL = 92,
        ADD_CALL_PARTICIPANT = 93,
        CALL_PARTICIPANT_JOINED = 94,
        REMOVE_CALL_PARTICIPANT = 95,
        TERMINATE_CALL = 96,
        MUTE_CALL_PARTICIPANT = 97,
        UNMUTE_CALL_PARTICIPANT = 98,
        ACTIVE_CALL_PARTICIPANTS =  110,
        CALL_SESSION_CREATED = 111,
        TURN_ON_VIDEO_CALL = 113,
        TURN_OFF_VIDEO_CALL = 114,
        START_RECORDING = 121,
        STOP_RECORDING = 122,
    }
}
